In [3]:
import pandas as pd

pd.__version__

'2.3.2'

In [4]:
df = pd.read_csv('car_fuel_efficiency.csv')

In [6]:
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [7]:
df.count()

engine_displacement    9704
num_cylinders          9222
horsepower             8996
vehicle_weight         9704
acceleration           8774
model_year             9704
origin                 9704
fuel_type              9704
drivetrain             9704
num_doors              9202
fuel_efficiency_mpg    9704
dtype: int64

In [10]:
fuel_type = df['fuel_type'].nunique()
fuel_type

2

In [12]:
missing_counts = df.isnull().sum()
num_col_missing = (missing_counts >0).sum()
num_col_missing

np.int64(4)

In [14]:
df['fuel_efficiency_mpg'].max()
asian_cars = df[df['origin'] == 'Asia']
max_asian_mpg = asian_cars['fuel_efficiency_mpg'].max()
max_asian_mpg

23.759122836520497

In [15]:
init_median = df['horsepower'].median()
init_median

149.0

In [17]:
most_val = df['horsepower'].mode()[0]
most_val

np.float64(152.0)

In [18]:
df['horsepower_imputed'] = df['horsepower'].fillna(most_val)
final_median = df['horsepower_imputed'].median()
final_median

152.0

In [19]:
asian_cars

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730
...,...,...,...,...,...,...,...,...,...,...,...
9688,260,4.0,NaN,3948.404625,15.5,2018,Asia,Diesel,All-wheel drive,-1.0,11.054830
9692,180,3.0,188.0,3680.341381,18.0,2016,Asia,Gasoline,Front-wheel drive,1.0,11.711653
9693,280,2.0,148.0,2545.070139,15.6,2012,Asia,Diesel,All-wheel drive,0.0,17.202782
9698,180,1.0,131.0,3107.427820,13.2,2005,Asia,Gasoline,Front-wheel drive,-2.0,13.933716
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [20]:
X_df = asian_cars[['vehicle_weight', 'model_year']]

In [21]:
X_df_subset = X_df.head(7)

In [25]:
X = X_df_subset.to_numpy()
print(f"1. Final Matrix X (Shape: {X.shape}):\n{X}\n")

1. Final Matrix X (Shape: (7, 2)):
[[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]

In [26]:
XT = X.T
XTX = XT @ X
print(f"2. Matrix XTX:\n{XTX}\n")

2. Matrix XTX:
[[62248334.33150762 41431216.50732678]
 [41431216.50732678 28373339.        ]]

In [30]:
import numpy as np
XTX_inv = np.linalg.inv(XTX)
print(f"3. Inverse of XTX (XTX_inv):\n{XTX_inv}\n")

3. Inverse of XTX (XTX_inv):
[[ 5.71497081e-07 -8.34509443e-07]
 [-8.34509443e-07  1.25380877e-06]]

In [31]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [32]:
w = XTX_inv @ XT @ y
print(f"5. Resulting vector w (Least Squares Weights):\n{w}\n")

5. Resulting vector w (Least Squares Weights):
[0.01386421 0.5049067 ]

In [34]:
sum_of_w = w.sum()

In [35]:
sum_of_w

np.float64(0.5187709081074007)